import type { Metadata } from "next";
import ToastProvider from "@/providers/toastProvider";
import "../../globals.css";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by Login",
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ margin: "0px", overflow: "hidden" }}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  )
}
